FROM node:22.14-alpine3.20 AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

RUN \
  if [ -f yarn.lock ]; then \
    yarn --frozen-lockfile; \
  elif [ -f pnpm-lock.yaml ]; then \
    corepack enable && \
    corepack prepare pnpm@10.12.1 --activate && \
    pnpm config set registry https://registry.npmjs.org/ && \
    pnpm config set fetch-retries 10 && \
    pnpm config set fetch-timeout 600000 && \
    pnpm install --frozen-lockfile --ignore-scripts=false; \
  else \
    echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN \
  if [ -f yarn.lock ]; then \
    yarn run build; \
  elif [ -f pnpm-lock.yaml ]; then \
    corepack enable && \
    corepack prepare pnpm@10.12.1 --activate && \
    pnpm run build; \
  else \
    echo "Lockfile not found." && exit 1; \
  fi

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

CMD ["node", "server.js"]